version: "3.9"

networks:
  my-b2b-network:

services:
  reimbursement:
    image: reimbursementapi
    ports:
      - 8080:8080
    container_name: reimbursement
    environment:
      - EmailAPI_URL=http://email:8081/email
    networks:
      - my-b2b-network
  email:
    image: emailapi
    container_name: email
    networks:
      - my-b2b-network