spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohammedbubshait95@gmail.com
    password: xdjxeodjczwtyvsi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    smtp:
      debug: true

  application:
    name: EmailAPI
  datasource:
    username: postgres
    password: p@$$w0rd123
    url: jdbc:postgresql://35.232.193.129:5432/postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
  servlet:
    context-path: